version: "3.9"

services:
  obsidian-sync-schedule:
    build:
      context: backend/
      dockerfile: ../docker/obsidian-sync/schedule/Dockerfile
    env_file:
      - ./backend/obsidian-sync/.env
    volumes:
      - ./backend/obsidian-sync/cert:/cert
      - ./logs/obsidian-sync/:/logs/
    restart: on-failure
    depends_on:
      - db
      - minio

  db:
    image: postgres:16.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  frontend: # nginx
    build:
      context: frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-k", "https://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3


volumes:
  pg_data:
  minio_data: