go-build-schedule:
	go build -o obsidian-sync-schedule cmd/cli/main.go

go-build-cli:
	go build -o obsidian-sync-cli cmd/server/main.go

go-run-cli:
	go run cmd/obsidian-sync-cli/main.go

go-run-schedule:
	go run cmd/obsidian-sync-schedule/main.go
