name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"
          cache: false

      - name: golangci-lint obsydian-sync
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./backend/obsidian-sync
          version: latest
          args: --timeout=5m
